### ISSUE TITLE
CMakeLists.txt 错误,跑不了

### ISSUE THREAD

**Issue by dasamanren** [clam314/LameMp3ForAndroid#1]
Error:A problem occurred configuring project ':app'.
> executing external native build for cmake C:\AndroidStudio_Worksplace\LameMp3ForAndroid-master\app\CMakeLists.txt
编辑不了
配置 classpath 'com.android.tools.build:gradle:2.3.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
我想拿到新版的so文件

**Comment by clam314** [comment]
编译出的so文件其实和SDK的版本关系不大。我已经修改了配置重新编译了，so文件也放到github上了，在...\app\lame\armeabi下
